version: '3'

tasks:
  default:
    deps:
      - install
  build:
    cmds:
      - nix build |& nom
    aliases:
      - b
  install:
    cmds:
      - nix profile upgrade --impure 0 |& nom
    aliases:
      - i
  run:
    cmds:
      - task: build
      - nix run
    aliases:
      - r
