version: '3'

tasks:
  default:
    deps:
      - install
  build:
    cmds:
      - nom build
    aliases:
      - b
  install:
    cmds:
      - task: build
      - nix profile upgrade --impure 0
      - notify-send --transient 'neovim be ready'
    aliases:
      - i
  run:
    cmds:
      - task: build
      - nix run
    aliases:
      - r
