version: '3'

tasks:
  default:
    deps:
      - run
  build:
    cmds:
      - nix build
    aliases:
      - b
  install:
    cmds:
      - nix profile upgrade --impure 0
    aliases:
      - i
  run:
    cmds:
      - nix run
    aliases:
      - r
