version: "3"

tasks:
  default:
    deps:
      - install
  build:
    cmds:
      - nom build --accept-flake-config
    aliases:
      - b
  install:
    cmds:
      - task: build
      - nix profile upgrade --accept-flake-config --impure 0
      - notify-send --transient 'neovim be ready'
    aliases:
      - i
  run:
    cmds:
      - task: build
      - nix run --accept-flake-config
    aliases:
      - r
