name: Push to cachix

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: cachix/cachix-action@v14
        with:
          name: willruggiano
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check --impure
      - run: nix build
      - run: cachix pin willruggiano nvim-drv "$(nix build --print-out-paths)"
