name: Push to cachix
on:
  push:
    branches: main

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: willruggiano
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .
      - run: nix flake check
